### ISSUE TITLE
maybe the wrong path?

### ISSUE THREAD

**Issue by ggfan** [dangfan/android-ndk-openssl#2]
Reading your great article: https://juejin.im/entry/56d7a4705bbb50004ca31cf5

from programing standing of point, it is fine.  In practice, it is too risky with this hack way though: if OS changes something for those 2 libs in next release, the app will not function at all. If really go this way ( using the existing lib baked inside OS image, but there is NDK header/so files ), probably use dlopen()/dlsym(). that way app at least get change to check whether the required functions are supported in the running OS; plus your APK size will be smaller -- you do not have to include them inside APK.

The proposed way in the article is too risky to be used in production application, might giving local developer community wrong direction... just my personal view.

Thanks

**Comment by dangfan** [comment]
Yes, you are right. Since Android 6.0, Google disallowed developers to use the embedded OpenSSL. Instead, developers should compile their own library. (https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html)
As a result, I have added explanation to my posts. However, the link you provided is not published by me. I'm sorry for the misunderstanding.
